variables:
- group: ServiceConnections
- name: azureSubscription
  value: $(ServiceConnectionPRD1)
- name: docker.imageName
  value: protectivemonitoringapi
- name: acr.azureContainerRegistryName
  value: prdrwdinfac1401
- name: acr.repositoryName
  value: protectivemonitoringapirepository
- name: serviceName
  value: prdrwdwebwa1403
